[tool.poetry]
name = "cvxbson"
version = "0.0.0"
description = "Dealing with json and bson files"
authors = ["Thomas Schmelzer"]
readme = "README.md"
repository = "https://github.com/cvxgrp/cvxbson"
packages = [{include = "cvx"}]
homepage = "https://www.cvxgrp.org/cvxbson"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numpy = "*"
numpyencoder = "*"
pyarrow = "*"
bson = "0.5.10"
typing_extensions = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.poetry.group.dev.dependencies]
loguru = "*"

[build-system]
requires = ["poetry>=1.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]
