[tool.poetry]
name = "cvxbson"
version = "0.0.0"
description = "Dealing with json and bson files"
authors = ["Thomas Schmelzer"]
readme = "README.md"
repository = "https://github.com/cvxgrp/cvxbson"
packages = [{include = "cvx"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
numpy = "*"
requests = "*"
numpyencoder = "*"
pyarrow = "*"
bson = "0.5.10"

[tool.poetry.group.test.dependencies]
pytest = "7.2.0"
pytest-cov = "4.0.0"

[tool.poetry.group.jupyter.dependencies]
jupyterlab = "*"
jupyter-book = "0.15.1"
pyyaml = "6.0"

[tool.peotry.group.linting.dependencies]
pylint = "*"
ruff = "0.0.277"
pre-commit = "*"
black = "23.3.0"

[tool.poetry.group.dev.dependencies]
loguru = "*"
fire = "*"

[tool.poetry.group.stubs.dependencies]
mypy = "*"

[tool.poetry.scripts]
weather-fire = "cli.weather_fire:main"
smallest-eigenvalue = "cli.smallest_eigenvalue:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 120
target-version = "py38"
exclude = [
    "*__init__.py"
]
