name: "book"

on:
  push:
    branches:
      - main


jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: cvxgrp/.github/actions/sphinx@main

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: cvxgrp/.github/actions/test@main

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: cvxgrp/.github/actions/jupyter@main

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx, jupyter]

    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      #- name: Download Book
        name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          #name: book
          path: .book

      #- uses: actions/download-artifact@v3
      #  with:
      #    name: sphinx
      #    path: .book/artifacts/sphinx

      #- uses: actions/download-artifact@v3
      #  with:
      #    name: tests
      #    path: .book/artifacts/tests
      - name: Inspect
        run: |
          ls -l .book
          ls -l .book/artifacts
          ls -l .book/artifacts/sphinx

      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages          # The branch the action should deploy to.
          folder: .book              # The folder the action should deploy.
