name: "book"

# This workflow builds and publishes documentation for the cvxbson repository
# It runs automatically on every push to the repository
# The workflow includes multiple documentation generation jobs and combines them into a final book

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

jobs:
  # Generates interactive Marimo notebooks for documentation
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: jebel-quant/marimushka@v0.1.1
        with:
          notebooks: 'book/marimo'


  # Runs tests and generates coverage reports for the source code
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/coverage@v2.2.8
        with:
          source-folder: 'src/cvx'
          tests-folder: 'tests'

  # Processes Jupyter notebooks for documentation
  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/jupyter@v2.2.8

  # Generates API documentation using pdoc for the source code
  pdoc:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/pdoc@v2.2.8
        with:
          source-folder: 'src/cvx'

  # Combines all documentation outputs into a final book
  # This job only runs after all other jobs have completed successfully
  # Requires permissions to write to repository contents and GitHub Pages
  book:
    runs-on: "ubuntu-latest"
    needs: [test, jupyter, marimo, pdoc]

    permissions:
      contents: write
      pages: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.8
