name: pre-commit

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/deptry@v2.0.17
        with:
          source-folder: 'src/cvx'

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/pre-commit@v2.0.17
