name: Bump version and publish

# This workflow creates a new version tag and publishes the package to PyPI
# It runs only when manually triggered via the GitHub Actions interface
# The workflow first creates a tag based on the repository's version information, then publishes to PyPI

on:
  workflow_dispatch

jobs:
  tag:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Tag
        uses: cvxgrp/.github/actions/tag@v2.2.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: tag
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: read
      # This permission is required for trusted publishing.
      id-token: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
